<?php

namespace ShrinkPress\Index\Assist;

class Internal
{
	/**
	* Is it an internal PHP function used by WordPress ?
	* @param string $func
	* @return boolean
	*/
	static function isInternal($func)
	{
		$func = (string) $func;
		return !empty(self::internal[ $func ]);
	}

	const internal = array(

		/* Core extension */
		'class_exists' => 1,
		'debug_backtrace' => 2,
		'define' => 3,
		'defined' => 4,
		'error_reporting' => 5,
		'extension_loaded' => 6,
		'func_get_arg' => 7,
		'func_get_args' => 8,
		'func_num_args' => 9,
		'function_exists' => 10,
		'gc_enabled' => 11,
		'get_class' => 12,
		'get_class_methods' => 13,
		'get_defined_constants' => 14,
		'get_object_vars' => 15,
		'get_resource_type' => 16,
		'is_a' => 17,
		'is_subclass_of' => 18,
		'method_exists' => 19,
		'restore_error_handler' => 20,
		'set_error_handler' => 21,
		'strcasecmp' => 22,
		'strcmp' => 23,
		'strlen' => 24,
		'strncmp' => 25,
		'trigger_error' => 26,
		'zend_version' => 27,

		/* standard extension */
		'abs' => 28,
		'addcslashes' => 29,
		'addslashes' => 30,
		'array_change_key_case' => 31,
		'array_column' => 32,
		'array_combine' => 33,
		'array_diff' => 34,
		'array_diff_assoc' => 35,
		'array_diff_key' => 36,
		'array_fill' => 37,
		'array_fill_keys' => 38,
		'array_filter' => 39,
		'array_flip' => 40,
		'array_intersect' => 41,
		'array_intersect_assoc' => 42,
		'array_intersect_key' => 43,
		'array_key_exists' => 44,
		'array_keys' => 45,
		'array_map' => 46,
		'array_merge' => 47,
		'array_merge_recursive' => 48,
		'array_pop' => 49,
		'array_push' => 50,
		'array_rand' => 51,
		'array_reduce' => 52,
		'array_replace_recursive' => 53,
		'array_reverse' => 54,
		'array_search' => 55,
		'array_shift' => 56,
		'array_slice' => 57,
		'array_splice' => 58,
		'array_sum' => 59,
		'array_unique' => 60,
		'array_unshift' => 61,
		'array_values' => 62,
		'array_walk' => 63,
		'arsort' => 64,
		'asort' => 65,
		'assert' => 66,
		'base64_decode' => 67,
		'base64_encode' => 68,
		'base_convert' => 69,
		'basename' => 70,
		'bin2hex' => 71,
		'bindec' => 72,
		'call_user_func' => 73,
		'call_user_func_array' => 74,
		'ceil' => 75,
		'chmod' => 76,
		'chr' => 77,
		'clearstatcache' => 78,
		'closedir' => 79,
		'compact' => 80,
		'constant' => 81,
		'copy' => 82,
		'count' => 83,
		'crc32' => 84,
		'current' => 85,
		'decbin' => 86,
		'dechex' => 87,
		'dirname' => 88,
		'disk_free_space' => 89,
		'doubleval' => 90,
		'end' => 91,
		'error_get_last' => 92,
		'error_log' => 93,
		'escapeshellarg' => 94,
		'explode' => 95,
		'extract' => 96,
		'fclose' => 97,
		'feof' => 98,
		'fflush' => 99,
		'fgets' => 100,
		'file' => 101,
		'file_exists' => 102,
		'file_get_contents' => 103,
		'file_put_contents' => 104,
		'filemtime' => 105,
		'fileowner' => 106,
		'fileperms' => 107,
		'filesize' => 108,
		'floatval' => 109,
		'flock' => 110,
		'floor' => 111,
		'flush' => 112,
		'fopen' => 113,
		'fread' => 114,
		'fseek' => 115,
		'fsockopen' => 116,
		'fstat' => 117,
		'ftell' => 118,
		'ftruncate' => 119,
		'fwrite' => 120,
		'get_html_translation_table' => 121,
		'getenv' => 122,
		'gethostbyaddr' => 123,
		'gethostbyname' => 124,
		'getimagesize' => 125,
		'gettype' => 126,
		'glob' => 127,
		'header' => 128,
		'header_remove' => 129,
		'headers_sent' => 130,
		'hexdec' => 131,
		'html_entity_decode' => 132,
		'htmlentities' => 133,
		'htmlspecialchars' => 134,
		'http_build_query' => 135,
		'ignore_user_abort' => 136,
		'image_type_to_mime_type' => 137,
		'implode' => 138,
		'in_array' => 139,
		'inet_ntop' => 140,
		'inet_pton' => 141,
		'ini_get' => 142,
		'ini_get_all' => 143,
		'ini_set' => 144,
		'intval' => 145,
		'ip2long' => 146,
		'iptcparse' => 147,
		'is_array' => 148,
		'is_bool' => 149,
		'is_callable' => 150,
		'is_dir' => 151,
		'is_file' => 152,
		'is_float' => 153,
		'is_int' => 154,
		'is_integer' => 155,
		'is_nan' => 156,
		'is_null' => 157,
		'is_numeric' => 158,
		'is_object' => 159,
		'is_readable' => 160,
		'is_resource' => 161,
		'is_scalar' => 162,
		'is_string' => 163,
		'is_uploaded_file' => 164,
		'is_writable' => 165,
		'is_writeable' => 166,
		'join' => 167,
		'key' => 168,
		'krsort' => 169,
		'ksort' => 170,
		'log' => 171,
		'log10' => 172,
		'ltrim' => 173,
		'max' => 174,
		'md5' => 175,
		'md5_file' => 176,
		'microtime' => 177,
		'min' => 178,
		'mkdir' => 179,
		'move_uploaded_file' => 180,
		'mt_rand' => 181,
		'natcasesort' => 182,
		'next' => 183,
		'number_format' => 184,
		'ob_clean' => 185,
		'ob_end_clean' => 186,
		'ob_end_flush' => 187,
		'ob_get_clean' => 188,
		'ob_get_flush' => 189,
		'ob_get_length' => 190,
		'ob_get_level' => 191,
		'ob_start' => 192,
		'opendir' => 193,
		'ord' => 194,
		'pack' => 195,
		'parse_str' => 196,
		'parse_url' => 197,
		'pathinfo' => 198,
		'phpinfo' => 199,
		'phpversion' => 200,
		'pow' => 201,
		'prev' => 202,
		'printf' => 203,
		'quoted_printable_decode' => 204,
		'rand' => 205,
		'range' => 206,
		'rawurlencode' => 207,
		'readdir' => 208,
		'readfile' => 209,
		'realpath' => 210,
		'register_shutdown_function' => 211,
		'reset' => 212,
		'rewind' => 213,
		'rmdir' => 214,
		'round' => 215,
		'rtrim' => 216,
		'scandir' => 217,
		'serialize' => 218,
		'set_time_limit' => 219,
		'setcookie' => 220,
		'sha1' => 221,
		'sha1_file' => 222,
		'shell_exec' => 223,
		'shuffle' => 224,
		'sizeof' => 225,
		'sleep' => 226,
		'sort' => 227,
		'sprintf' => 228,
		'stat' => 229,
		'str_ireplace' => 230,
		'str_pad' => 231,
		'str_repeat' => 232,
		'str_replace' => 233,
		'str_split' => 234,
		'strcspn' => 235,
		'stream_context_create' => 236,
		'stream_context_get_options' => 237,
		'stream_context_set_option' => 238,
		'stream_get_contents' => 239,
		'stream_get_meta_data' => 240,
		'stream_get_wrappers' => 241,
		'stream_set_chunk_size' => 242,
		'stream_set_read_buffer' => 243,
		'stream_set_timeout' => 244,
		'stream_socket_client' => 245,
		'strip_tags' => 246,
		'stripcslashes' => 247,
		'stripos' => 248,
		'stripslashes' => 249,
		'stristr' => 250,
		'strnatcasecmp' => 251,
		'strpbrk' => 252,
		'strpos' => 253,
		'strrchr' => 254,
		'strrev' => 255,
		'strripos' => 256,
		'strrpos' => 257,
		'strspn' => 258,
		'strstr' => 259,
		'strtok' => 260,
		'strtolower' => 261,
		'strtoupper' => 262,
		'strtr' => 263,
		'strval' => 264,
		'substr' => 265,
		'substr_count' => 266,
		'substr_replace' => 267,
		'sys_get_temp_dir' => 268,
		'tempnam' => 269,
		'touch' => 270,
		'trim' => 271,
		'uasort' => 272,
		'ucfirst' => 273,
		'ucwords' => 274,
		'uksort' => 275,
		'umask' => 276,
		'uniqid' => 277,
		'unlink' => 278,
		'unpack' => 279,
		'unserialize' => 280,
		'urldecode' => 281,
		'urlencode' => 282,
		'usort' => 283,
		'version_compare' => 284,
		'vsprintf' => 285,
		'wordwrap' => 286,

		/* SPL extension */
		'spl_autoload_register' => 287,
		'spl_object_hash' => 288,

		/* date extension */
		'checkdate' => 289,
		'date' => 290,
		'date_create' => 291,
		'date_create_immutable_from_format' => 292,
		'date_default_timezone_set' => 293,
		'gmdate' => 294,
		'gmmktime' => 295,
		'mktime' => 296,
		'strftime' => 297,
		'strtotime' => 298,
		'time' => 299,
		'timezone_identifiers_list' => 300,
		'timezone_offset_get' => 301,
		'timezone_open' => 302,
		'timezone_transitions_get' => 303,

		/* libxml extension */
		'libxml_clear_errors' => 304,
		'libxml_disable_entity_loader' => 305,
		'libxml_get_last_error' => 306,

		/* openssl extension */
		'openssl_decrypt' => 307,
		'openssl_encrypt' => 308,
		'openssl_get_cipher_methods' => 309,
		'openssl_x509_parse' => 310,

		/* pcre extension */
		'preg_match' => 311,
		'preg_match_all' => 312,
		'preg_quote' => 313,
		'preg_replace' => 314,
		'preg_replace_callback' => 315,
		'preg_split' => 316,

		/* zlib extension */
		'gzdecode' => 317,
		'gzdeflate' => 318,
		'gzencode' => 319,
		'gzinflate' => 320,
		'gzuncompress' => 321,

		/* ctype extension */
		'ctype_digit' => 322,

		/* curl extension */
		'curl_close' => 323,
		'curl_errno' => 324,
		'curl_error' => 325,
		'curl_exec' => 326,
		'curl_getinfo' => 327,
		'curl_init' => 328,
		'curl_multi_add_handle' => 329,
		'curl_multi_close' => 330,
		'curl_multi_exec' => 331,
		'curl_multi_info_read' => 332,
		'curl_multi_init' => 333,
		'curl_multi_remove_handle' => 334,
		'curl_setopt' => 335,
		'curl_version' => 336,

		/* hash extension */
		'hash' => 337,
		'hash_algos' => 338,
		'hash_file' => 339,
		'hash_final' => 340,
		'hash_init' => 341,
		'hash_update' => 342,

		/* fileinfo extension */
		'finfo_close' => 343,
		'finfo_file' => 344,
		'finfo_open' => 345,
		'mime_content_type' => 346,

		/* gd extension */
		'imagealphablending' => 347,
		'imagecopy' => 348,
		'imagecopyresampled' => 349,
		'imagecreatefromgif' => 350,
		'imagecreatefromjpeg' => 351,
		'imagecreatefrompng' => 352,
		'imagecreatefromstring' => 353,
		'imagecreatetruecolor' => 354,
		'imagedestroy' => 355,
		'imagegif' => 356,
		'imagejpeg' => 357,
		'imagepng' => 358,
		'imagerotate' => 359,
		'imagesavealpha' => 360,
		'imagesx' => 361,
		'imagesy' => 362,
		'imagetypes' => 363,

		/* iconv extension */
		'iconv' => 364,
		'iconv_mime_decode' => 365,

		/* json extension */
		'json_decode' => 366,
		'json_encode' => 367,

		/* mbstring extension */
		'mb_check_encoding' => 368,
		'mb_convert_encoding' => 369,
		'mb_detect_encoding' => 370,
		'mb_detect_order' => 371,
		'mb_get_info' => 372,
		'mb_internal_encoding' => 373,
		'mb_list_encodings' => 374,
		'mb_strtolower' => 375,

		/* mysqli extension */
		'mysqli_affected_rows' => 376,
		'mysqli_character_set_name' => 377,
		'mysqli_close' => 378,
		'mysqli_connect_errno' => 379,
		'mysqli_connect_error' => 380,
		'mysqli_errno' => 381,
		'mysqli_error' => 382,
		'mysqli_fetch_array' => 383,
		'mysqli_fetch_field' => 384,
		'mysqli_fetch_object' => 385,
		'mysqli_free_result' => 386,
		'mysqli_get_client_info' => 387,
		'mysqli_get_server_info' => 388,
		'mysqli_init' => 389,
		'mysqli_insert_id' => 390,
		'mysqli_more_results' => 391,
		'mysqli_next_result' => 392,
		'mysqli_num_fields' => 393,
		'mysqli_ping' => 394,
		'mysqli_query' => 395,
		'mysqli_real_connect' => 396,
		'mysqli_real_escape_string' => 397,
		'mysqli_select_db' => 398,
		'mysqli_set_charset' => 399,

		/* SimpleXML extension */
		'simplexml_load_string' => 400,

		/* exif extension */
		'exif_imagetype' => 401,
		'exif_read_data' => 402,

		/* tokenizer extension */
		'token_get_all' => 403,

		/* xml extension */
		'utf8_decode' => 404,
		'utf8_encode' => 405,
		'xml_error_string' => 406,
		'xml_get_current_byte_index' => 407,
		'xml_get_current_column_number' => 408,
		'xml_get_current_line_number' => 409,
		'xml_get_error_code' => 410,
		'xml_parse' => 411,
		'xml_parse_into_struct' => 412,
		'xml_parser_create' => 413,
		'xml_parser_create_ns' => 414,
		'xml_parser_free' => 415,
		'xml_parser_set_option' => 416,
		'xml_set_character_data_handler' => 417,
		'xml_set_default_handler' => 418,
		'xml_set_element_handler' => 419,
		'xml_set_end_namespace_decl_handler' => 420,
		'xml_set_object' => 421,
		'xml_set_start_namespace_decl_handler' => 422,

		/* mcrypt extension */
		'mcrypt_create_iv' => 423,

		/* xdiff extension */
		'xdiff_string_diff' => 424,

		/* FPM extension */
		'fastcgi_finish_request' => 425,

		/* OPcache extension */
		'opcache_invalidate' => 426,

		/* Apache extension */
		'apache_get_modules' => 427,

		/* Ignore extension */
		'debug' => 428,

		/* Dunno what happened, didn't detected those as internal */
		'fputs' => -1,
		'socket_set_option' => -1,
		'socket_last_error' => -1,
		'socket_strerror' => -1,
		'socket_close' => -1,
		'socket_create' => -1,
		'socket_connect' => -1,
		'socket_read' => -1,
		'socket_write' => -1,
		'socket_getsockname' => -1,
		'socket_bind' => -1,
		'socket_listen' => -1,
		'socket_accept' => -1,
		'sscanf' => -1,
		'is_long' => -1,
		'decoct' => -1,
		'getcwd' => -1,
		'dl' => -1,
		'PclErrorCode' => -1,
		'PclErrorString' => -1,
		'is_link' => -1,
		'gzopen' => -1,
		'gzputs' => -1,
		'gzclose' => -1,
		'getdate' => -1,
		'Chr' => -1,
		'gzread' => -1,
		'Ord' => -1,
		'PclError' => -1,
		'PclErrorReset' => -1,
		'gzwrite' => -1,
		'rename' => -1,
		'php_uname' => -1,
		'gd_info' => -1,
		'exec' => -1,
		'php_sapi_name' => -1,
		'mysql_get_client_info' => -1,
		'chdir' => -1,
		'chgrp' => -1,
		'chown' => -1,
		'posix_getpwuid' => -1,
		'filegroup' => -1,
		'posix_getgrgid' => -1,
		'fileatime' => -1,
		'dir' => -1,
		'ftp_ssl_connect' => -1,
		'ftp_connect' => -1,
		'ftp_login' => -1,
		'ftp_pasv' => -1,
		'ftp_get_option' => -1,
		'ftp_set_option' => -1,
		'ftp_fget' => -1,
		'ftp_fput' => -1,
		'ftp_pwd' => -1,
		'ftp_chdir' => -1,
		'ftp_site' => -1,
		'ftp_chmod' => -1,
		'ftp_rename' => -1,
		'ftp_delete' => -1,
		'ftp_rmdir' => -1,
		'ftp_nlist' => -1,
		'ftp_mdtm' => -1,
		'ftp_size' => -1,
		'ftp_mkdir' => -1,
		'ftp_systype' => -1,
		'ftp_rawlist' => -1,
		'ftp_close' => -1,
		'ssh2_connect' => -1,
		'ssh2_auth_password' => -1,
		'ssh2_auth_pubkey_file' => -1,
		'ssh2_sftp' => -1,
		'ssh2_exec' => -1,
		'stream_set_blocking' => -1,
		'ssh2_sftp_realpath' => -1,
		'ssh2_sftp_rename' => -1,
		'ssh2_sftp_unlink' => -1,
		'ssh2_sftp_rmdir' => -1,
		'ssh2_sftp_mkdir' => -1,
		'mysql_get_server_info' => -1,
		'date_default_timezone_get' => -1,
		'natsort' => -1,
		'sodium_crypto_sign_verify_detached' => -1,
		'setlocale' => -1,
		'crypt' => -1,
		'mail' => -1,
		'imap_rfc822_parse_adrlist' => -1,
		'property_exists' => -1,
		'filter_var' => -1,
		'idn_to_ascii' => -1,
		'escapeshellcmd' => -1,
		'popen' => -1,
		'pclose' => -1,
		'ctype_alnum' => -1,
		'openssl_pkcs7_sign' => -1,
		'openssl_error_string' => -1,
		'get_magic_quotes_runtime' => -1,
		'set_magic_quotes_runtime' => -1,
		'chunk_split' => -1,
		'quoted_printable_encode' => -1,
		'gethostname' => -1,
		'rawurldecode' => -1,
		'openssl_pkey_get_private' => -1,
		'openssl_get_md_methods' => -1,
		'openssl_sign' => -1,
		'openssl_pkey_free' => -1,
		'openssl_pkey_get_details' => -1,
		'openssl_private_encrypt' => -1,
		'settype' => -1,
		'socket_set_blocking' => -1,
		'var_export' => -1,
		'stream_socket_enable_crypto' => -1,
		'each' => -1,
		'is_executable' => -1,
		'socket_set_timeout' => -1,
		'chop' => -1,
		'socket_get_status' => -1,
		'json_last_error' => -1,
		'mb_stripos' => -1,
		'imageantialias' => -1,
		'imagecolorallocatealpha' => -1,
		'imageistruecolor' => -1,
		'imagecolorstotal' => -1,
		'imagetruecolortopalette' => -1,
		'ob_get_contents' => -1,
		'htmlspecialchars_decode' => -1,
		'libxml_use_internal_errors' => -1,
		'simplexml_import_dom' => -1,
		'count_chars' => -1,
		'array_count_values' => -1,
		'is_double' => -1,

		'json_last_error_msg' => -1,
		'rsort' => -1,
		'mysql_set_charset' => -1,
		'mysql_query' => -1,
		'mysql_result' => -1,
		'mysql_select_db' => -1,
		'mysql_real_escape_string' => -1,
		'mysql_error' => -1,
		'mysql_free_result' => -1,
		'mysql_connect' => -1,
		'mysql_ping' => -1,
		'mysql_errno' => -1,
		'mysql_affected_rows' => -1,
		'mysql_insert_id' => -1,
		'mysql_fetch_object' => -1,
		'mysql_client_encoding' => -1,
		'mysql_num_fields' => -1,
		'mysql_fetch_field' => -1,
		'mysql_close' => -1,
	);
}
